<a href="https://colab.research.google.com/github/jelly-decoder28/compbioworkshop/blob/main/Lists%2C_Tuples%2C_Dicts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lists and loops

In [ ]:
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
print(weekdays)

# try it out: sort weekdays alphabetically, then print the sorted list
# Remember that the sort method works "in place"

weekdays.sort()
print(weekdays)

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
['Friday', 'Monday', 'Thursday', 'Tuesday', 'Wednesday']


In [ ]:
for day in weekdays:
    print(day)

Friday
Monday
Thursday
Tuesday
Wednesday


In [ ]:
num_list = [5, 9, 2.3, 14, 3, 2, 10]

# try it out: use a for loop to print the squared value of each number in num_list

for i in num_list:
    print(i**2)

25
81
5.289999999999999
196
9
4
100


In [ ]:
# Run this cell: notice that there's no output because we're just defining the function

def list_mean(input_list):
    # the code below will run each time we use this function
    return sum(input_list) / len(input_list)

In [ ]:
# try it out: use list_mean on a list of numbers of your own choosing

my_numbers = [1, 1, 2, 3, 5, 8, 13]

print(len(my_numbers))
print(list_mean(my_numbers))

7
4.714285714285714


In [ ]:
# We're re-defining list_mean now

def list_mean(input_list):
    # the code below will run each time we use this function
    print("The input list was:", input_list)
    return sum(input_list)/len(input_list)

In [ ]:
list_one = [1, 4, 10, 2]
list_two = [4, 5, 2, 1]

# try it out: add the averages of list_one and list_two
print(list_mean(list_one))
print(list_mean(list_two))

The input list was: [1, 4, 10, 2]
4.25
The input list was: [4, 5, 2, 1]
3.0


In [ ]:
string_tuple = ('a', 'b', 'c')  # a tuple of strings
num_tuple = (5, 9, 2.3, 14, 3, 2, 10)  # a tuple of numerics

print(string_tuple)
print(num_tuple)

# get the third item in the string_tuple
print(string_tuple[2])

# or the second item in the num_tuple (remember, python indexing begins with 0!)
print(num_tuple[1])

('a', 'b', 'c')
(5, 9, 2.3, 14, 3, 2, 10)
c
9


In [ ]:
# lists ['a', 'b', 'c', 'd']
# tuple ('a', 'b', 'c', 'd')
#              ^
#         0    1    2    3
#             [1]

In [ ]:
def len_and_mean(input_list):
    list_length = len(input_list)
    list_average = sum(input_list)/len(input_list)

    # You can return multiple values by separating them with a comma
    return list_length, list_average

# len_and_mean(some_list) --> (5, 2.3)

In [ ]:
# try it out: use len_and_mean on a list of numerics of your own choosing

my_numbers = [2, 4, 5.5, 8, 10]
len_and_mean(my_numbers)

(5, 5.9)

In [ ]:
repeat_list = [1, 5, 2, 11, 2, 6, 6, 9, 1, 2, 0, 6, 11, 2, -3, 1]

# What if we just want unique values?
set(repeat_list)

{-3, 0, 1, 2, 5, 6, 9, 11}

In [ ]:
# count number of unique elements in repeat_list
print(len(repeat_list))
print(len(set(repeat_list)))

16
8


In [ ]:
# list   ['a', 'b', 'c']
# tuple  ('a', 'b', 'c')
# inxex    0    1    2

# dict  {'a': 1, 'b': 2}
#        ['a'] --> 1

In [ ]:
# Dictionaries are defined in key-value pairs
# Below, our dates are keys and the weekday is the value

days_and_dates = {
    '08/05': 'Monday',
    '08/06': 'Tuesday',
    '08/07': 'Wednesday',
    '08/08': 'Thursday',
    '08/09': 'Friday',
    '08/10': 'Saturday',
    '08/11': 'Sunday',
    '08/12': 'Monday'
}

days_and_dates

{'08/05': 'Monday',
 '08/06': 'Tuesday',
 '08/07': 'Wednesday',
 '08/08': 'Thursday',
 '08/09': 'Friday',
 '08/10': 'Saturday',
 '08/11': 'Sunday',
 '08/12': 'Monday'}

In [ ]:
# This will return the value associated with the key '08/06'.
days_and_dates['08/06']

'Tuesday'

In [ ]:
bootcamp_dates = ['01/13', '01/14', '01/15', '01/16', '01/17']
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

# Use bootcamp_dates as the list of keys, and weekdays as the list of values
bootcamp_dict = dict(zip(bootcamp_dates, weekdays))
print(bootcamp_dict)

{'01/13': 'Monday', '01/14': 'Tuesday', '01/15': 'Wednesday', '01/16': 'Thursday', '01/17': 'Friday'}


In [ ]:
alphabet = "abcdefghijklmnopqrstuvwxyz"
alphabet = list(alphabet)

# indexes = range(start, stop, step)
indexes = range(0, 26, 1)

alphabet_dict = dict(zip(alphabet, indexes))
alphabet_dict

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [ ]:
# Make sure to run this cell!
import numpy as np

# check that the package was installed by printing the version
print(np.__version__)

1.26.4


In [ ]:
num_list = [5, 9, 2.3, 14, 3, 2, 10]

print('Mean:', np.mean(num_list))
print('Median:', np.median(num_list))

Mean: 6.471428571428571
Median: 5.0


In [ ]:
# try it out:

# Write a function called summarize_list that will take a list of numerics
# and return a tuple with:
# 1) the length of the list
# 2) the median of the list, using np.median
# 3) the mean of the list, using np.mean

def summarize_list(my_list):
    list_len = len(my_list)
    list_median = np.median(my_list)
    list_mean = np.mean(my_list)
    return list_len, list_median, list_mean

In [ ]:
# test the function here
x = summarize_list(num_list)
x[1]


5.0

In [ ]:
range(0, 10, 2)

range(0, 10, 2)

In [ ]:
# For example
mixed_ints = [1, 5, 2, 3, 3, 5, 8, 10, 7, 8]
print(mixed_ints)
print(np.unique(mixed_ints))

[1, 5, 2, 3, 3, 5, 8, 10, 7, 8]
[ 1  2  3  5  7  8 10]


Let's quickly look at the documentation for `np.unique()`. To learn more about a function and its inputs  and outputs within Google Colab, you can simply type `?` followed by the name of the function.



In [ ]:
?np.unique

In [ ]:
# Use np.unique on mixed_ints, setting return_counts = True
np.unique(mixed_ints, return_counts=True)

(array([ 1,  2,  3,  5,  7,  8, 10]), array([1, 1, 2, 2, 1, 2, 1]))

In [ ]:
# creating an array from a list
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
print(weekdays)
weekday_array = np.array(weekdays)

weekday_array

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']


array(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      dtype='<U9')

In [ ]:
# Get the length of the array
print('Length:', len(weekday_array))
# Retrieve Tuesday by index
print(weekday_array[1])
# Iterate over the array
for day in weekday_array:
    print(day, 'is', len(day), 'characters long.')

Length: 5
Tuesday
Monday is 6 characters long.
Tuesday is 7 characters long.
Wednesday is 9 characters long.
Thursday is 8 characters long.
Friday is 6 characters long.


In [ ]:
one_by_five = np.array([1, 1, 1, 1, 1])
print('Starting array:\n', one_by_five)

Starting array:
 [1 1 1 1 1]


In [ ]:
# As a nested list: two sub-lists of length 5
print('Nested list:', [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]], '\n')

two_by_five = np.array([[1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1]])
print('2 x 5 array:\n', two_by_five, '\n')

# As a nested list: five sub-lists of length 5
five_by_five = np.array([[1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1],
                         [1, 1, 1, 1, 1]])
print('5 x 5 array:\n', five_by_five)

Nested list: [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]] 

2 x 5 array:
 [[1 1 1 1 1]
 [1 1 1 1 1]] 

5 x 5 array:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
five_by_five_array = np.array(
    [
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]
    ]
)

print((five_by_five_array / 2)**2)

[[0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]]


In [ ]:
(1 / 2) ** 2

0.25

In [ ]:
five_by_five_list = [[1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1]]

#(five_by_five_list/2)**2
def nested_half_square(input_nested_list):
    # a function that does the same thing as above for a nested list
    # we index each sublist, then each item in the list, and then perform our operation

    for sublist in input_nested_list:
        for index in range(len(sublist)):
            # here, the range object is similar to a list or tuple of integers ranging from 0 to 4
            sublist[index] = (sublist[index]/2)**2
    return input_nested_list

nested_half_square(five_by_five_list)

[[0.25, 0.25, 0.25, 0.25, 0.25],
 [0.25, 0.25, 0.25, 0.25, 0.25],
 [0.25, 0.25, 0.25, 0.25, 0.25],
 [0.25, 0.25, 0.25, 0.25, 0.25],
 [0.25, 0.25, 0.25, 0.25, 0.25]]

In [ ]:
weekdays = ["Monday", "Tuesday"]
weekends = ["Sautrday", "Sunday"]

week = [weekdays, weekends]
np.array(week)

array([['Monday', 'Tuesday'],
       ['Sautrday', 'Sunday']], dtype='<U8')

In [ ]:
# try it out:
# use np.array on a mixed list of:
# 1) integers and strings
# 2) integers and floats
# 3) floats and strings
# 4) integers, floats, and strings
l1 = [1, 2, 3, 'four']
l2 = [1, 2, 3.6, 4.3]
l3 = [1.0, 2.0, 3.0, 'four']
l4 = [1, 2.2, 3.3, 'four']


In [ ]:
print(np.array(l1))
print(np.array(l2))
print(np.array(l3))
print(np.array(l4))

['1' '2' '3' 'four']
[1.  2.  3.6 4.3]
['1.0' '2.0' '3.0' 'four']
['1' '2.2' '3.3' 'four']


In [ ]:
# Below, just write five_by and then pause. You can also press control+space to trigger auto-complete
five_by_five
five_by_five

In [ ]:
print('Array:\n', five_by_five)

print(len(five_by_five))  # this only gives us the number of rows

Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
5


In [ ]:
# The size attribute describes the number of elements in the array
# We access it with .size

print('Array:\n', five_by_five)

print('Number of elements:', five_by_five.size)

Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Number of elements: 25


In [ ]:
five_by_five.size

25

In [ ]:
# try it out: how many rows/columns are in five_by_five?

print("five_by_five has this number of rows:", five_by_five.shape[1])
print("five_by_five has this number of columns:", five_by_five.shape[0])

five_by_five has this number of rows: 5
five_by_five has this number of columns: 5


In [ ]:
five_by_five.shape

(5, 5)

In [ ]:
five_by_five.ndim

2

In [ ]:
one_to_five = np.array([1, 2, 3, 4, 5])

# try it out:
# print the last value of the array
print(one_to_five[-1])

# print the last three values of the array
print(one_to_five[-3:])

5
[3 4 5]


In [ ]:
# a nested list: each sub-list has 5 elements
one_to_fifteen_list = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
]
print('Nested list:', one_to_fifteen_list)

# the second sub-list is index [1]
print('\nSecond sub-list:')
print(one_to_fifteen_list[1])

# the last element of the second sublist is [1][4]
print('\nSecond sub-list, last element:')
print(one_to_fifteen_list[1][4])

# the last three elements of the second sublist are [1][2:]
print('\nSecond sub-list, last three elements:')
print(one_to_fifteen_list[1][2:])

Nested list: [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

Second sub-list:
[6, 7, 8, 9, 10]

Second sub-list, last element:
10

Second sub-list, last three elements:
[8, 9, 10]


In [ ]:
# array version of above nested list
one_to_fifteen_array = np.array(one_to_fifteen_list)
print('Array:\n', one_to_fifteen_array)

# the second row is index [1]
print('\nSecond row:')
print(one_to_fifteen_array[1])

# the last element of the second row is [1, 4]
print('\nSecond row, last element:')
print(one_to_fifteen_array[1, 4])

# the last three elements of the second row are [1, 2:]
print('\nSecond row, last three elements:')
print(one_to_fifteen_array[1, 2:])

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Second row:
[ 6  7  8  9 10]

Second row, last element:
10

Second row, last three elements:
[ 8  9 10]


In [ ]:
# print array again for convenient viewing
print('Array:\n', one_to_fifteen_array)

# print the fourth column of the array
print('\nFourth column:')
one_to_fifteen_array[:, 3] # ':' is a placeholder for "all rows"

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Fourth column:


array([ 4,  9, 14])

In [ ]:
# print array again for convenient viewing
print('Array:\n', one_to_fifteen_array)

print('\nMiddle three elements of the first two rows:')
# rows: 0, 1
# columns: 1, 2, 3
one_to_fifteen_array[:2, 1:4]

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Middle three elements of the first two rows:


array([[2, 3, 4],
       [7, 8, 9]])

In [ ]:
# print array again for convenient viewing
print('Array:\n', one_to_fifteen_array)

print('\nOnly the first, third, and fifth columns')
one_to_fifteen_array[:, (0, 2, 4)]

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Only the first, third, and fifth columns


array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [ ]:
### write your code below ###

nested_lists_even = [
    [2, 4, 6, 8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
]

even_3x4 = np.array(nested_lists_even)
print(even_3x4)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [ ]:
# access the relevant attribute for even_3x4

### write your code below ###

print(even_3x4.nbytes)

96


In [ ]:
### write your code below ###

print(even_3x4)
np.mean(even_3x4, axis=0)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


array([10., 12., 14., 16.])

In [ ]:
# a. create a 2x4 array filled with random numbers between 0 and 4 (included)

# [0, 1]  -- *4 --> [0, 4]

### write your code below ###
rng = np.random.default_rng()
rand_array_2x4 = rng.random(size=(2, 4))
rand_array_2x4 = rand_array_2x4 * 4
print(rand_array_2x4)

[[1.45166408 2.45146774 1.69207146 1.93115469]
 [2.84412035 3.83638259 0.74805166 3.53613145]]


In [ ]:
# b. create an array like the one above (i.e. same shape) that is filled with zeros

### write your code below ###

# first way
# np.zeros((2, 4))

# second way
# np.zeros(rand_array_2x4.shape)

# third way
np.zeros_like(rand_array_2x4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# c. use numpy to answer the following question: are a and b element-wise equal?
# Note: "element-wise equal" means all their elements are equal.

### write your code below ###

# a = rng.random(size=(2, 4))
a = np.zeros((2, 4))
b = np.zeros((2, 4))

print("array a\n", a)
print("array b\n", b)

# a == b
np.array_equal(a, b)

array a
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array b
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


False

In [ ]:
# d. print a 1D array that contains the values in the 2D array below but with no duplicates

some_array = np.array(
    [
        [1, 28, 9, 3, 66],
        [2, 3, 14, 9, 29],
        [5, 5, 1, 41, 28],
    ]
)

### write your code below ###

np.unique(some_array)

array([ 1,  2,  3,  5,  9, 14, 28, 29, 41, 66])

In [ ]:
# e. limit the values in the array from part a by constraining them to be in the interval [1,3]
# (i.e. any value less than 1 is replaced with a 1 and any value greater than 3 is replaced with a 3)

### write your code below ###
rng = np.random.default_rng()
rand_array_2x4 = rng.random(size=(2, 4))
rand_array_2x4 = rand_array_2x4 * 4
print(rand_array_2x4)

# first way
# rand_array_2x4 = np.where(rand_array_2x4 < 1, 1, rand_array_2x4)
# rand_array_2x4 = np.where(rand_array_2x4 > 3, 3, rand_array_2x4)
# print(rand_array_2x4)

# second way
np.clip(rand_array_2x4, 1, 3)

# f. use numpy to revert the casing in the string array below (uppercase become lowercase and vice versa)


### write your code below ###


[[2.26317975 1.82148218 0.05607719 3.74300581]
 [3.42564936 3.88299928 2.44502833 3.2314573 ]]


array([[2.26317975, 1.82148218, 1.        , 3.        ],
       [3.        , 3.        , 2.44502833, 3.        ]])

In [ ]:
?np.clip

In [ ]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

In [ ]:
?np.eye

In [ ]:
?np.nonzero

In [ ]:
### write your code below ###

def off_diagonals(my_array):
    diag_aray =  np.eye(my_array.shape[0])
    diag_aray = diag_aray - 1
    return my_array[np.nonzero(diag_aray)]



In [ ]:
# Execute this cell after having defined off_diagonals above and make sure it passes
test_mat = np.array([[1, 2, 5, 12],
                     [5, 8, 10, 3],
                     [15, 2, 21, 4],
                     [8, 9, 11, 3]])

print('Test mat: \n', test_mat, '\n')

print('Off diagonal entries: \n', off_diagonals(test_mat))

assert(all(off_diagonals(test_mat) == [2.0, 5.0, 12.0, 5.0, 10.0, 3.0, 15.0, 2.0, 4.0, 8.0, 9.0, 11.0]))

Test mat: 
 [[ 1  2  5 12]
 [ 5  8 10  3]
 [15  2 21  4]
 [ 8  9 11  3]] 

Off diagonal entries: 
 [ 2  5 12  5 10  3 15  2  4  8  9 11]


In [ ]:
### edit the skeleton code below ###

def translate(seq):
    # we've created an amino acid dictionary for you already
    amino_dict = {'AAA': 'K', 'AAC': 'N', 'AAG': 'K', 'AAU': 'N',
           'ACA': 'T', 'ACC': 'T', 'ACG': 'T', 'ACU': 'T',
           'AGA': 'R', 'AGC': 'S', 'AGG': 'R', 'AGU': 'S',
           'AUA': 'I', 'AUC': 'I', 'AUG': 'M', 'AUU': 'I',
           'CAA': 'Q', 'CAC': 'H', 'CAG': 'Q', 'CAU': 'H',
           'CCA': 'P', 'CCC': 'P', 'CCG': 'P', 'CCU': 'P',
           'CGA': 'R', 'CGC': 'R', 'CGG': 'R', 'CGU': 'R',
           'CUA': 'L', 'CUC': 'L', 'CUG': 'L', 'CUU': 'L',
           'GAA': 'E', 'GAC': 'D', 'GAG': 'E', 'GAU': 'D',
           'GCA': 'A', 'GCC': 'A', 'GCG': 'A', 'GCU': 'A',
           'GGA': 'G', 'GGC': 'G', 'GGG': 'G', 'GGU': 'G',
           'GUA': 'V', 'GUC': 'V', 'GUG': 'V', 'GUU': 'V',
           'UAA': '_', 'UAC': 'Y', 'UAG': '_', 'UAU': 'Y',
           'UCA': 'S', 'UCC': 'S', 'UCG': 'S', 'UCU': 'S',
           'UGA': '_', 'UGC': 'C', 'UGG': 'W', 'UGU': 'C',
           'UUA': 'L', 'UUC': 'F', 'UUG': 'L', 'UUU': 'F'}

  ### write your code below ###


In [ ]:
# try it out with translation_seq when you're done
translation_seq = 'AACGTCAATGTATCACGCGACTAGCCTCTGCTTAATTTTTGTGCTCAAGGGTTTTGGTCCGCCCGAGCGGTGCAGCCGATTAGGACCATGTAATACATTTGTTACAAGACTTCTTTTAAACACTTAG'

print(translate(translation_seq))
print(translate("AAGACAUGGCACUGGAGCGCGGGGUCAGCAGCUACGCUUAA"))

In [ ]:
# everything below is instantiated in the global environment

dog_breeds = ['shiba inu', 'corgi', 'pug']
dog_counts = [6, 2, 3]
dog_record = dict(zip(dog_breeds, dog_counts))

In [ ]:
def doggy_daycare(breeds, counts):
    dog_breeds = breeds
    dog_counts = counts
    dog_record = dict(zip(breeds, counts))

    return dog_record

When run, `doggy_daycare()` creates variables named `dog_breeds`, `dog_counts`, and `dog_record`. How will these local variables interact with their identically named global counterparts?

In [ ]:
print('Global dog_record:', dog_record)
print('dog_record, local to doggy_daycare:', doggy_daycare(['german shepherd', 'husky'], [3, 2]))
print('Global dog_record is unchanged:', dog_record)

In [ ]:
def daycare_report():
    daycare_greeting = "Have a paw-some day!"
    print("We have", sum(dog_counts), "dogs today.")
    print(daycare_greeting)

daycare_report()
print(daycare_greeting)